### ISSUE TITLE
Use filters in Events and Members

### ISSUE THREAD

**Issue by Piwakk** [Mines-Paristech-Students/Portail-des-eleves#272]
TEDLT

**Comment by Piwakk** [comment]
Events: #280

**Comment by delmaass** [comment]
I think there is an issue with the Event filtering when there is no events for an association. The Event view returns an error whereas this error doesn't occur when we remove the filter from the view. Can someone reproduce this issue on his side ?

========================

[04/Sep/2021 12:22:01] "GET /api/v1/associations/pages/?association_id=anonymines&page_type=STATIC&page=1 HTTP/1.1" 200 507
Internal Server Error: /api/v1/associations/events/
Traceback (most recent call last):
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.SyntaxError: ERREUR:  constante non entière dans GROUP BY
LINE 1: ...timestamptz)) GROUP BY "associations_event"."id", NULL) subq...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\rest_framework\viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\rest_framework\mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\rest_framework\generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\rest_framework\pagination.py", line 206, in paginate_queryset
    self.page = paginator.page(page_number)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\core\paginator.py", line 70, in page
    number = self.validate_number(number)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\core\paginator.py", line 48, in validate_number
    if number > self.num_pages:
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\core\paginator.py", line 97, in num_pages
    if self.count == 0 and not self.allow_empty_first_page:
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\utils\functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\core\paginator.py", line 91, in count
    return c()
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\db\models\query.py", line 392, in count
    return self.query.get_count(using=self.db)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\db\models\sql\query.py", line 504, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\db\models\sql\query.py", line 489, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\db\models\sql\compiler.py", line 1140, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Utilisateur\miniconda3\envs\portail\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: ERREUR:  constante non entière dans GROUP BY
LINE 1: ...timestamptz)) GROUP BY "associations_event"."id", NULL) subq...

**Comment by delmaass** [comment]
Issue solved. The order_by method had some troubles ordering when the queryset was empty. I will PR soon
