### ISSUE TITLE
Blackend check: error before checking

### ISSUE THREAD

**Issue by delmaass** [Mines-Paristech-Students/Portail-des-eleves#329]
There seems to be an issue with Blackend check which crashes before the checking step. See the last PRs for more details.

`Run black --check backend
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.4/x64/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/black.py", line 4134, in patched_main
    patch_click()
  File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/black.py", line 4123, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/site-packages/click/__init__.py)
Error: Process completed with exit code 1.`

**Comment by abocquet** [comment]
Cf https://github.com/psf/black/issues/2964 for a fix
